-- ============================================================
-- V1: cria a tabela tasks
-- Portável entre H2 (modo PostgreSQL) e PostgreSQL real.
-- ============================================================

CREATE TABLE tasks (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    description   VARCHAR(500),
    status        VARCHAR(20)  NOT NULL,
    priority      VARCHAR(10)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    completed_at  TIMESTAMP
);

-- Índices pra acelerar os filtros já implementados na API
CREATE INDEX idx_tasks_status   ON tasks (status);
CREATE INDEX idx_tasks_priority ON tasks (priority);
CREATE INDEX idx_tasks_created  ON tasks (created_at DESC);