# Este Secret armazena as credenciais do banco de dados PostgreSQL para o ambiente de desenvolvimento.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: productivity-dev
type: Opaque
stringData:
  # stringData: K8s codifica em base64 sozinho.
  # Em produção, esses valores viriam de Vault/Sealed Secrets/External Secrets,
  # não em YAML versionado. Aqui é só pra dev local.
  POSTGRES_DB: productivity
  POSTGRES_USER: productivity
  POSTGRES_PASSWORD: changeme